# Generated by Django 4.2 on 2023-04-29 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publication',
            new_name='BlogPost',
        ),
    ]
